#ifndef LIBVIRT_GO_STORAGE_VOLUME_COMPAT_H__
#define LIBVIRT_GO_STORAGE_VOLUME_COMPAT_H__

/* 1.3.2 */

#ifndef VIR_STORAGE_VOL_WIPE_ALG_TRIM
#define VIR_STORAGE_VOL_WIPE_ALG_TRIM 9
#endif


/* 1.3.4 */

#ifndef VIR_STORAGE_VOL_PLOOP
#define VIR_STORAGE_VOL_PLOOP 5
#endif

#endif /* LIBVIRT_GO_STORAGE_VOLUME_COMPAT_H__ */
